[phases.setup]
nixPkgs = ["...", "postgresql"]

[phases.build]
cmds = [
  "bundle install --deployment --without development test",
  "bundle exec rake assets:precompile",
  "bundle exec bootsnap precompile app/ lib/"
]

[start]
cmd = "bundle exec puma -C config/puma.rb"
