FROM ruby:3.2.2-slim

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    libpq-dev \
    git \
    curl \
    libvips \
    postgresql-client \
    node-gyp \
    pkg-config \
    python-is-python3 \
    libyaml-dev \
    gnupg2 \
    cron \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g yarn

WORKDIR /rails

RUN gem install bundler

COPY Gemfile Gemfile.lock ./

RUN bundle config set --global force_ruby_platform true && \
    bundle config set --global build.pg --with-pg-config=/usr/bin/pg_config && \
    bundle install

COPY . .

COPY entrypoint.dev.sh /usr/bin/entrypoint.dev.sh
COPY entrypoint.dev.bat /usr/bin/entrypoint.dev.bat
RUN chmod +x /usr/bin/entrypoint.dev.sh

ENTRYPOINT ["/bin/sh", "-c", "if [ -f /usr/bin/entrypoint.dev.sh ]; then /usr/bin/entrypoint.dev.sh \"$@\"; else /usr/bin/entrypoint.dev.bat \"$@\"; fi"]

RUN chown -R root:root /rails && \
    chmod -R 755 /rails

CMD ["rails", "server", "-b", "0.0.0.0"] 